ARG PYCA_RELEASE
FROM quay.io/pypa/${PYCA_RELEASE}
ARG PYCA_RELEASE
MAINTAINER Python Cryptographic Authority
WORKDIR /root
RUN \
  if [ $(uname -m) = "x86_64" ]; \
  then \
    if stat /etc/redhat-release 1>&2 2>/dev/null; then \
      yum -y install prelink && \
      yum -y clean all && \
      rm -rf /var/cache/yum; \
    elif stat /etc/debian_version 1>&2 2>/dev/null; then \
      export DEBIAN_FRONTEND=noninteractive && \
      apt-get update -qq && \
      apt-get install -qq -y --no-install-recommends prelink && \
      apt-get clean -qq && \
      rm -rf /var/lib/apt/lists/*; \
    else \
      echo "This is alpine and we don't need any more packages"; \
    fi; \
  fi

# This is done as two separate steps because prelink is not available on
# aarch64, and libffi-dev/devel isn't required on x86_64 (since wheels exist)
RUN \
  if [ $(uname -m) = "aarch64" ]; \
  then \
    if stat /etc/redhat-release 1>&2 2>/dev/null; then \
      yum -y install libffi-devel && \
      yum -y clean all && \
      rm -rf /var/cache/yum; \
    elif stat /etc/debian_version 1>&2 2>/dev/null; then \
      export DEBIAN_FRONTEND=noninteractive && \
      apt-get update -qq && \
      apt-get install -qq -y --no-install-recommends libffi-dev && \
      apt-get clean -qq && \
      rm -rf /var/lib/apt/lists/*; \
    else \
      echo "This is alpine and we don't need any more packages"; \
    fi; \
  fi

ADD install_openssl.sh /root/install_openssl.sh
ADD openssl-version.sh /root/openssl-version.sh
RUN ./install_openssl.sh

# Install PyPy
RUN \
  if [ $(uname -m) = "x86_64" ]; then \
    if stat /etc/alpine-release 1>&2 2>/dev/null; then \
      echo 'Skip building musl PyPy wheels for now'; \
    else \
      curl https://downloads.python.org/pypy/pypy3.6-v7.3.3-linux64.tar.bz2 | tar jxf - -C /opt/ && \
        mv /opt/pypy3.6* /opt/pypy3.6; \
      curl https://downloads.python.org/pypy/pypy3.7-v7.3.6-linux64.tar.bz2 | tar jxf - -C /opt/ && \
        mv /opt/pypy3.7* /opt/pypy3.7; \
      curl https://downloads.python.org/pypy/pypy3.8-v7.3.6-linux64.tar.bz2 | tar jxf - -C /opt/ && \
        mv /opt/pypy3.8* /opt/pypy3.8; \
    fi; \
  fi

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable --profile minimal
ENV PATH="/root/.cargo/bin:$PATH"
