language: generic
sudo: required

services:
    - docker

script: ./build-images.py

notifications:
    irc:
        channels:
            - "irc.freenode.org#cryptography-dev"
        use_notice: true
        skip_join: true
