#!/bin/sh

set -e
set -x

if [ "$#" -ne "2" ]; then
    echo "Usage: $0 KEY VALUE" 1>&2
    exit 1
fi

ansible-playbook -i ansible/hosts \
    --extra-vars "SECRET_KEY=$1 SECRET_VALUE=$2" \
    ansible/production-secret.yml
