trigger: none
pr: none

jobs:
    - job: 'macOS'
      pool:
          vmImage: 'macOS-10.14'
      strategy:
          matrix:
              Python27:
                  python.version: '2.7'
                  PYTHON_DOWNLOAD_URL: "https://www.python.org/ftp/python/2.7.16/python-2.7.16-macosx10.6.pkg"
                  PYTHON_BIN_PATH: /Library/Frameworks/Python.framework/Versions/2.7/bin/python
              Python34:
                  python.version: '3.4'
                  PYTHON_DOWNLOAD_URL: "https://www.python.org/ftp/python/3.4.4/python-3.4.4-macosx10.6.pkg"
                  PYTHON_BIN_PATH: /Library/Frameworks/Python.framework/Versions/3.4/bin/python3
              Python35:
                  python.version: '3.5'
                  PYTHON_DOWNLOAD_URL: "https://www.python.org/ftp/python/3.5.4/python-3.5.4-macosx10.6.pkg"
                  PYTHON_BIN_PATH: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3
              Python36:
                  python.version: '3.6'
                  PYTHON_DOWNLOAD_URL: "https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.6.pkg"
                  PYTHON_BIN_PATH: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
              Python37:
                  python.version: '3.7'
                  PYTHON_DOWNLOAD_URL: "https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.6.pkg"
                  PYTHON_BIN_PATH: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
      steps:
          - script: |
              set -e
              set -x
              curl "$PYTHON_DOWNLOAD_URL" -o python.pkg
              sudo installer -pkg python.pkg -target /
            displayName: Download and install Python

          - script: |
              set -e
              set -x
              # This is done via get-pip because Python 3.4/3.5 are linked against
              # an ancient OpenSSL so we have no TLS 1.2 unless we upgrade pip
              # (which uses the SecureTransport ctypes shim)
              curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
              $PYTHON_BIN_PATH get-pip.py
            displayName: Upgrade pip
          - script: $PYTHON_BIN_PATH -m pip install -U virtualenv
            displayName: Install virtualenv
          - script: $PYTHON_BIN_PATH -m virtualenv .venv
            displayName: Create virtualenv
          - script: .venv/bin/pip install -U wheel
            displayName: Update wheel to the latest version
          - script: .venv/bin/pip install pycparser
            displayName: Install our Python dependencies

          - script: |
              set -e
              set -x
              .venv/bin/pip wheel cffi --wheel-dir=wheelhouse --no-binary cffi
            displayName: Build the wheel
          - script: .venv/bin/pip install --no-index -f wheelhouse cffi
            displayName: Test installing the wheel
          - script: |
              .venv/bin/python -c "import cffi;print(cffi.__version__)"
            displayName: Print the cffi version
          - task: PublishBuildArtifacts@1
            inputs:
                pathToPublish: wheelhouse/
                artifactName: cffi-macos-python$(python.version)

    - job: 'manylinux1'
      pool:
          vmImage: 'ubuntu-16.04'
      container: 'pyca/cryptography-manylinux1:x86_64'
      strategy:
          matrix:
              Python27m:
                  PYTHON_VERSION: 'cp27-cp27m'
              Python27mu:
                  PYTHON_VERSION: 'cp27-cp27mu'
              Python34m:
                  PYTHON_VERSION: 'cp34-cp34m'
              Python35m:
                  PYTHON_VERSION: 'cp35-cp35m'
              Python36m:
                  PYTHON_VERSION: 'cp36-cp36m'
              Python37m:
                  PYTHON_VERSION: 'cp37-cp37m'
      steps:
          - script: /opt/python/$PYTHON_VERSION/bin/python -m virtualenv .venv
            displayName: Create virtualenv
          - script: .venv/bin/pip install pycparser
            displayName: Install our Python dependencies
          - script: |
              set -e
              set -x
              .venv/bin/pip wheel --no-binary cffi --no-deps cffi -w tmpwheelhouse/
            displayName: Build the wheel
          - script: auditwheel repair tmpwheelhouse/cffi*.whl -w wheelhouse/
            displayName: Run auditwheel
          - script: .venv/bin/pip install cffi --no-index -f wheelhouse/
            displayName: Test installing the wheel
          - script: |
              .venv/bin/python -c "import cffi;print(cffi.__version__)"
            displayName: Print the cffi version
          - task: PublishBuildArtifacts@1
            inputs:
                pathToPublish: wheelhouse/
                artifactName: cffi-manylinux1-$(PYTHON_VERSION)

    - job: 'windows'
      pool:
          vmImage: 'windows-2019'
      container: $[variables.containerImage]
      strategy:
          matrix:
              Python27-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py27-x86'
                  PYTHON_VERSION: '27'
                  WINDOWS_ARCH: 'x86'
              Python27-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py27-x86_64'
                  PYTHON_VERSION: '27'
                  WINDOWS_ARCH: 'x86_64'
              Python34-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py34-x86'
                  PYTHON_VERSION: '34'
                  WINDOWS_ARCH: 'x86'
              Python34-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py34-x86_64'
                  PYTHON_VERSION: '34'
                  WINDOWS_ARCH: 'x86_64'
              Python35-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py35-x86'
                  PYTHON_VERSION: '35'
                  WINDOWS_ARCH: 'x86'
              Python35-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py35-x86_64'
                  PYTHON_VERSION: '35'
                  WINDOWS_ARCH: 'x86_64'
              Python36-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86'
                  PYTHON_VERSION: '36'
                  WINDOWS_ARCH: 'x86'
              Python36-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86_64'
                  PYTHON_VERSION: '36'
                  WINDOWS_ARCH: 'x86_64'
              Python37-x86:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86'
                  PYTHON_VERSION: '37'
                  WINDOWS_ARCH: 'x86'
              Python37-x86-64:
                  containerImage: 'pyca/cryptography-runner-windows:py3-x86_64'
                  PYTHON_VERSION: '37'
                  WINDOWS_ARCH: 'x86_64'
      steps:
          - script: '"C:/Python%PYTHON_VERSION%/Scripts/pip" install pycparser'
            displayName: Install our Python dependencies
          - script: |
                    C:/Python%PYTHON_VERSION%/Scripts/pip wheel cffi --wheel-dir=wheelhouse --no-binary cffi
            displayName: Build the wheel
          - script: '"C:/Python%PYTHON_VERSION%/Scripts/pip" install -f wheelhouse cffi --no-index'
            displayName: Test installing the wheel
          - script: |
              "C:/Python%PYTHON_VERSION%/python" -c "import cffi;print(cffi.__version__)"
            displayName: Print the cffi version
          - script: mkdir cffi-wheelhouse
            displayName: Create a directory for placing the final wheel in
          - script: move wheelhouse\cffi*.whl cffi-wheelhouse\
            displayName: Move the cffi wheel into the final wheel house
          - task: PublishBuildArtifacts@1
            inputs:
                pathToPublish: cffi-wheelhouse/
                artifactName: cffi-windows-$(WINDOWS_ARCH)-python$(PYTHON_VERSION)
