apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: kube-runner
spec:
  replicas: 2
  template:
    spec:
      organization: pyca
      dockerVolumeMounts:
        - mountPath: /var/lib/docker
          name: docker
      volumes:
        - name: docker
          emptyDir:
            medium: Memory
      ephemeral: true # recommended to not leak data between builds.
