apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: kube-runner
spec:
  replicas: 2
  template:
    spec:
      #repository: pyca/cryptography
      organization: pyca
