---
- hosts: "*"
  remote_user: root
  tasks:
    - name: ensure docker is running
      service:
          name: docker
          state: started
          enabled: yes
    - name: install the systemd service files
      copy:
          src: "systemd/{{ item }}.service"
          dest: /etc/systemd/system/{{ item }}.service
      with_items:
          - caddy
          - jenkins
    - name: "ensure {{ item }} is running"
      service:
          name: "{{ item }}"
          state: started
          enabled: yes
      with_items:
          - caddy
          - jenkins
