---
- hosts: "*"
  remote_user: root
  vars:
      services:
          - caddy
          - jenkins
  tasks:
    - name: ensure docker is running
      service:
          name: docker
          state: started
          enabled: yes
    - name: install the python-docker package
      apt:
          name: python-docker
          state: present
    - name: pull the latest docker images
      docker_image:
          name: "{{ item }}"
          force: true
      with_items:
          - pyca/caddy
          - pyca/crypto-jenkins
      notify:
          - restart caddy
          - restart jenkins
    - name: install the systemd service files
      copy:
          src: "systemd/{{ item }}.service"
          dest: /etc/systemd/system/{{ item }}.service
      with_items: "{{ services }}"
      notify:
          - restart caddy
          - restart jenkins
    - name: "ensure the services are running"
      systemd:
          name: "{{ item }}"
          state: started
          enabled: yes
      with_items: "{{ services }}"
  handlers:
    - name: restart caddy
      systemd:
          name: caddy
          daemon_reload: yes
          state: restarted
    - name: restart jenkins
      systemd:
          name: jenkins
          daemon_reload: yes
          state: restarted
