---
- hosts: "*"
  remote_user: root
  vars:
      services:
          - caddy
      # This variable is needed to tell docker swarm init what the
      # advertise address should be. bond0 is what we use for onmetal
      swarm_advertise_addr: bond0
  tasks:
    - name: install the docker configuration file
      copy:
          src: "docker/daemon.json"
          dest: "/etc/docker/daemon.json"
      notify:
          - restart docker
    - name: ensure docker is running
      service:
          name: docker
          state: started
          enabled: yes
    - name: install the python-docker package
      apt:
          name: python-docker
          state: present
    - name: pull the latest docker images
      docker_image:
          name: "{{ item }}"
          force: true
      with_items:
          - pyca/caddy
      notify:
          - restart caddy
    - name: install the systemd service files
      copy:
          src: "systemd/{{ item }}.service"
          dest: /etc/systemd/system/{{ item }}.service
      with_items: "{{ services }}"
      notify:
          - restart caddy
    - name: "ensure the services are running"
      systemd:
          name: "{{ item }}"
          state: started
          enabled: yes
      with_items: "{{ services }}"
    - command: docker info
      register: docker_info
    - name: "set up a single node docker swarm"
      # docker swarm needs a single address to advertise its existence.
      # Our server, however, has two addresses. By specifying an explicit
      # named interface on the server we make docker happy.
      command: "docker swarm init --advertise-addr {{ swarm_advertise_addr }}"
      when: "'Swarm: active' not in docker_info.stdout"
  handlers:
    - name: restart docker
      systemd:
          name: docker
          daemon_reload: yes
          state: restarted
    - name: restart caddy
      systemd:
          name: caddy
          daemon_reload: yes
          state: restarted
