---
- hosts: "*"
  remote_user: root
  vars:
      services:
          - caddy
          - jenkins
  tasks:
    - name: ensure docker is running
      service:
          name: docker
          state: started
          enabled: yes
    - name: install the systemd service files
      copy:
          src: "systemd/{{ item }}.service"
          dest: /etc/systemd/system/{{ item }}.service
      with_items: "{{ services }}"
      notify:
          - restart caddy
          - restart jenkins
    - name: "ensure the services are running"
      service:
          name: "{{ item }}"
          state: started
          enabled: yes
      with_items: "{{ services }}"
  handlers:
    - name: restart caddy
      service: name=caddy state=restarted
    - name: restart jenkins
      service: name=jenkins state=restarted
