on:
  pull_request:
    paths:
      - '.github/workflows/build-openssl.yml'
      - 'windows/openssl/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-openssl.yml'
      - 'windows/openssl/**'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ARCH: ["win32", "win64"]
        MSVC_VERSION: ["2010", "2019"]
    name: "Build OpenSSL for ${{ matrix.ARCH }} on MSVC ${{ matrix.MSVC_VERSION }}"
    steps:
      - uses: actions/checkout@master
      - run: choco install -y nasm winrar
      - name: Install MSVC 2010
        run: powershell -Command windows\openssl\install_tools.ps1 -InstallURI https://download.microsoft.com/download/F/1/0/F10113F5-B750-4969-A255-274341AC6BCE/GRMSDK_EN_DVD.iso
        if: matrix.MSVC_VERSION == '2010'
      - name: Install nmake
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify `
           --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" `
           --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --passive --norestart
        shell: powershell
        if: matrix.MSVC_VERSION == '2019'
      - name: Download OpenSSL source
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; wget 'https://www.openssl.org/source/openssl-1.1.1f.tar.gz' -OutFile 'openssl-latest.tar.gz'
          if ((Get-FileHash openssl-latest.tar.gz -Algorithm SHA256).Hash -ne "186c6bfe6ecfba7a5b48c47f8a1673d0f3b0e5ba2e25602dd23b629975da3f35") {
              Write-Error 'Hashes do not match' -ErrorAction Stop
          }
        shell: powershell
      - run: '"C:\Program Files\WinRAR\WinRAR.exe" -INUL x openssl-latest.tar.gz'
        shell: cmd
      - run: windows\openssl\build_openssl.bat ${{ matrix.ARCH }} ${{ matrix.MSVC_VERSION }}
        shell: cmd
      - uses: actions/upload-artifact@v1
        with:
          name: "openssl-${{ matrix.ARCH }}-${{ matrix.MSVC_VERSION }}"
          path: build\
