on:
  pull_request: {}

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ARCH: ["win32", "win64"]
        MSVC_VERSION: ["2010", "2019"]
    name: "Build OpenSSL for ${{ matrix.ARCH }} on MSVC ${{ matrix.MSVC_VERSION }}"
    steps:
      - uses: actions/checkout@master
      - run: choco install -y nasm activeperl winrar
      - run: powershell -Command windows\openssl\install_tools.ps1 -InstallURI https://download.microsoft.com/download/F/1/0/F10113F5-B750-4969-A255-274341AC6BCE/GRMSDK_EN_DVD.iso
        if: ${{ matrix.MSVC_VERSION }} == "2010"
      - run: wget -O openssl-latest.tar.gz https://www.openssl.org/source/openssl-1.1.1-latest.tar.gz
      - run: "C:\Program Files\WinRAR\WinRAR.exe" -INUL x openssl-latest.tar.gz
        shell: cmd
      - run: windows\openssl\build_openssl.bat ${{ matrix.ARCH }} ${{ matrix.MSVC_VERSION }}
        shell: cmd
      - uses: actions/upload-artifact@v1
        with:
          name: "openssl-${{ matrix.ARCH }}-${{ matrix.MSVC_VERSION }}.zip"
          path: C:\build\