name: Terraform

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  push:
    branches:
      - main
    paths:
      - terraform/
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3.1.2
      - run: terraform -chdir=terraform/ fmt -check
      - run: terraform -chdir=terraform/ init -backend=false
      # Need to have a values.yaml for validate to pass.
      - run: cp terraform/values.yaml.template terraform/values.yaml
      - run: terraform -chdir=terraform/ validate
